apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::613622767668:role/eksctl-brain-tasks-eks-nodegroup-b-NodeInstanceRole-K1dQWTORphf1
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::613622767668:role/codebuild-brain-tasks-role
      username: codebuild
      groups:
        - system:masters
